global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - __CONFIG_DIR__/alerts.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['127.0.0.1:9093']
scrape_configs:
  - job_name: api-manager
    __METRICS_AUTH__
    static_configs:
      - targets: ['127.0.0.1:__API_PORT__']
