auth_enabled: false
server:
  http_listen_address: 127.0.0.1
  http_listen_port: 3200
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 127.0.0.1:4317
        http:
          endpoint: 127.0.0.1:4318
ingester:
  max_block_duration: 5m
compactor:
  compaction:
    block_retention: 168h
storage:
  trace:
    backend: local
    local:
      path: __DATA_DIR__/tempo/traces
    wal:
      path: __DATA_DIR__/tempo/wal
