DROP TABLE IF EXISTS api_releases;
ALTER TABLE apis DROP COLUMN IF EXISTS auth_config;
ALTER TABLE apis DROP COLUMN IF EXISTS daily_quota;
ALTER TABLE apis DROP COLUMN IF EXISTS monthly_quota;
ALTER TABLE apis DROP COLUMN IF EXISTS upstream_url;
ALTER TABLE apis DROP COLUMN IF EXISTS upstream_path;
ALTER TABLE apis DROP COLUMN IF EXISTS strip_path;
