import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {validPassword} from '../lib/account-validation.ts';
const source=readFileSync(new URL('../components/account-experience.tsx',import.meta.url),'utf8');
test('user center stores no login, TOTP or recovery secrets in browser storage',()=>{assert.doesNotMatch(source,/localStorage|sessionStorage|dangerouslySetInnerHTML/);assert.match(source,/credentials:'same-origin'/);assert.match(source,/cache:'no-store'/);assert.match(source,/api-manager-auth/)});
test('CAPTCHA is per-action, OAuth has none and security only challenges password change',()=>{assert.match(source,/epoch,reset/);assert.match(source,/expired-callback/);assert.match(source,/error-callback/);assert.match(source,/finally\{captcha.reset\(\)\}/);assert.doesNotMatch(source,/oauthCaptcha|emailCaptcha|totpCaptcha|profileCaptcha/);assert.match(source,/operation==='password'&&confirmationMethod!=='passkey'&&<Captcha/)});
test('buying and revoking require explicit confirmation and purchase retry reuses operation',()=>{assert.match(source,/确认购买套餐/);assert.match(source,/确认 \/ 重试此购买/);assert.match(source,/operation_id:purchase.operation/);assert.match(source,/吊销调用凭据/);assert.match(source,/manageCaptcha/)});
test('critical profile changes include password, MFA and mailbox proofs',()=>{assert.match(source,/value.verification_code=fields.get\('code'\)/);assert.match(source,/current_password/);assert.match(source,/totp_code/);assert.match(source,/email!==sentEmail/);assert.match(source,/登录验证|双重验证/);assert.match(source,/reset_password/)});

test('password length matches the 8 to 24 character form policy',()=>{assert.equal(validPassword('1234567'),false);assert.equal(validPassword('12345678'),true);assert.equal(validPassword('中文密'),false);assert.equal(validPassword('中文'),false);assert.equal(validPassword('密'.repeat(24)),true);assert.equal(validPassword('密'.repeat(25)),false);assert.equal(validPassword('12345678!<>"&'),true);assert.doesNotMatch(source,/minLength=\{8\}/)});

test('account changes destroy secrets, log state and pending confirmation dialogs',()=>{assert.match(source,/identity.current!==next.uid/);assert.match(source,/<CallLogs key=\{profile.uid\}/);assert.match(source,/<Keys key=\{profile.uid\}/);assert.match(source,/setRecovery\(\[\]\)/)});

test('credential secret stays in the dialog and loading does not unmount the directory',()=>{assert.match(source,/setVisibleKey\(result.api_key\)/);assert.match(source,/复制密钥/);assert.match(source,/dataLoading&&<span className="account-loading-indicator"/);assert.doesNotMatch(source,/dataLoading\?<p/);assert.match(source,/新建调用凭据/)});
test('actions and navigation require explicit account permissions',()=>{for(const p of ['account.keys.write','account.keys.reveal','account.billing.purchase','account.billing.redeem','account.security'])assert.ok(source.includes(p));assert.match(source,/重置密钥/);assert.match(source,/confirm:true/);assert.match(source,/siteDateInputToISO/);assert.match(source,/PlanUsage/);assert.match(source,/卡密兑换/)});
test('plan card layout does not reintroduce the stretched single-card override',()=>{const css=readFileSync(new URL('../app/account/account.css',import.meta.url),'utf8');assert.doesNotMatch(css,/account-plan-card:only-child/);assert.match(css,/account-plan-price strong\{white-space:nowrap/)});

test('identity binding has a dedicated authenticated flow and returns to security',()=>{assert.match(source,/provider\+'\/link'/);assert.doesNotMatch(source,/provider\+'\/start','POST',\{purpose:'link'/);assert.match(source,/get\('view'\)==='security'/);assert.match(source,/list.includes\(linked\)/);assert.match(source,/query.delete\('linked'\)/)});
test('identity status errors never look like an unbound account',()=>{assert.match(source,/identityStatus==='loading'/);assert.match(source,/identityStatus==='error'\?'绑定状态暂不可用'/);assert.match(source,/disabled=\{busy\|\|identityStatus!=='ready'\}/);assert.match(source,/重新读取绑定状态/);assert.match(source,/window.addEventListener\('focus',update\)/);assert.doesNotMatch(source,/api<string\[\]>\('\/account\/v1\/identities'\)\.then.*catch\(\(\)=>\{\}\)/)});
