import {normalizeEmailDomains} from '../lib/account-validation.ts';
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
test('password login is primary and recovery is only next to password submit',()=>{const s=read('../components/account-experience.tsx');assert.match(s,/auth-submit-primary/);assert.match(s,/auth-recovery-button/);assert.match(s,/step==='login'&&mode==='password'&&recoverable/);assert.doesNotMatch(s,/没有账号？创建账号/);assert.match(s,/\(step==='login'\|\|step==='register'\)/)});
test('supported email suffixes can only be selected and verification send stays by code',()=>{const s=read('../components/email-field.tsx'),auth=read('../components/account-experience.tsx');assert.match(s,/<select name="email_domain"/);assert.match(s,/domains.map/);assert.match(s,/<input type="hidden" name="email" value=\{value\}/);assert.match(s,/pattern="\[\^\\s@\]\+"/);assert.match(auth,/className="email-code-row"/);assert.match(auth,/>发送<\/button>/)});
test('IP restriction copy describes public egress and valid single/CIDR syntax',()=>{const s=read('../components/account-experience.tsx');assert.match(s,/operation==='policy'\?'设置此密钥允许的调用来源/);for(const value of ['203.0.113.10','203.0.113.0/24','2001:db8::/48','不要填写端口、网址或域名','公网出口地址'])assert.ok(s.includes(value))});
test('Telegram configuration includes the secret and preview accepts scroll input without scripts',()=>{const account=read('../../internal/web/assets/account.js'),css=read('../../internal/web/assets/app.css'),extra=read('../../internal/web/assets/enhancements.js');assert.match(account,/telegram_secret:values.telegram_secret/);assert.match(css,/pointer-events:auto;background:#fff/);assert.match(extra,/sandbox="" tabindex="0"/);assert.match(extra,/openResetUserTwoFactor/)});

test('email suffix policy accepts null and absent configuration without crashing forms',()=>{assert.deepEqual(normalizeEmailDomains(null),[]);assert.deepEqual(normalizeEmailDomains(undefined),[]);assert.deepEqual(normalizeEmailDomains([]),[]);assert.deepEqual(normalizeEmailDomains(['gmail.com','outlook.com']),['gmail.com','outlook.com']);assert.match(read('../components/email-field.tsx'),/normalizeEmailDomains\(configuredDomains\)/)});

test('Telegram email binding explanation is on registration only',()=>{const s=read('../components/account-experience.tsx');assert.match(s,/step==='register'&&options.telegram&&<p className="account-note">首次使用 Telegram/);assert.doesNotMatch(s,/step==='login'&&options.telegram&&<p className="account-note">/)});

test('console access is obtained from the user center rather than a direct admin link',()=>{const auth=read('../components/account-experience.tsx'),html=read('../../internal/web/assets/index.html'),js=read('../../internal/web/assets/app.js');assert.match(auth,/api<\{url:string\}>\('\/account\/v1\/admin-entry','POST'/);assert.doesNotMatch(auth,/<a href=\{adminPath/);assert.doesNotMatch(html,/id="login-form"/);assert.doesNotMatch(js,/async function login\(/);assert.match(js,/location.replace\('\/login\?return=admin'\)/);assert.match(auth,/destination==='admin'\)location.assign\('\/account'\)/)});

test('nested user editors return to their parent without losing the selected tab',()=>{const js=read('../../internal/web/assets/app.js'),extra=read('../../internal/web/assets/enhancements.js'),plans=read('../../internal/web/assets/consolidation.js');assert.match(js,/if \(!force\) void modal\._onReturn\?\.\(\)/);assert.match(js,/data-profile-modal-cancel>\$\{onReturn\?'返回':'取消'\}/);assert.match(js,/data-role-modal-cancel>\$\{onReturn\?'返回':'取消'\}/);assert.match(extra,/openUserEditor\(fresh,state\.cache\.userRoles\|\|roles,activeTab\)/);assert.match(extra,/epoch!==authEpoch/);assert.match(plans,/openPlanBinding\(userId='',onReturn\)/);assert.match(plans,/data-close-binding>\$\{onReturn\?'返回':'取消'\}/)});
test('loading states reserve space without visible transient loading sentences',()=>{const s=read('../components/account-experience.tsx'),css=read('../app/styles.css');assert.match(s,/<LoadingPlaceholder className="account-loading-shell"/);assert.match(s,/account-loading-indicator/);assert.doesNotMatch(s,/<p role="status">正在读取/);assert.match(css,/\.ui-placeholder\{[^}]*min-height:380px/);assert.match(read('../components/loading-placeholder.tsx'),/aria-busy="true"/) });
test('public password copy is plain and new usernames are bounded and alphanumeric',()=>{const s=read('../components/account-experience.tsx'),onboarding=read('../app/complete-registration/page.tsx');assert.match(s,/用户名或邮箱/);assert.match(s,/\[a-zA-Z0-9\]\{3,20\}/);assert.match(s,/8–24 个字符/);assert.doesNotMatch(s+onboarding,/UTF-8|字节|8–72/);assert.match(s,/step==='login'\?72:24/);assert.match(onboarding,/maxLength=\{24\}/) });
