import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
const source=readFileSync(new URL('../../internal/web/assets/passkeys.js',import.meta.url),'utf8');
function client(fetch){const document={documentElement:{},querySelector:()=>null,addEventListener:()=>{}};const window={isSecureContext:true,PublicKeyCredential:function(){}};const credential={id:'test',rawId:new Uint8Array([1,2,3]).buffer,type:'public-key',authenticatorAttachment:'platform',response:{clientDataJSON:new Uint8Array([1]).buffer,authenticatorData:new Uint8Array([2]).buffer,signature:new Uint8Array([3]).buffer,userHandle:null},getClientExtensionResults:()=>({})};const context={window,document,navigator:{credentials:{get:async()=>credential,create:async()=>credential}},fetch,location:{origin:'https://example.test'},URL,Request,FormData,Uint8Array,atob,btoa,structuredClone,AbortSignal,crypto:webcrypto,MutationObserver:class{observe(){}}};vm.runInNewContext(source,context);return window.APIManagerPasskeys}
test('passkey confirmation freezes method destination and exact body without persisting secrets',async()=>{const calls=[];const tools=client(async(path,init)=>{const data=JSON.parse(init.body);calls.push({path,data});return {ok:true,json:async()=>path.endsWith('/begin')?{challenge_id:'challenge',options:{publicKey:{challenge:'AQID',allowCredentials:[],rpId:'example.test'}}}:{confirmation:'one-use-proof'}}});const request=await tools.prepare('/admin/v1/database/reveal',{method:'POST',body:JSON.stringify({current_password:'',__passkey:true,value:'<script>'}),headers:{'Content-Type':'application/json'}});assert.equal(request.headers.get('X-Passkey-Confirmation'),'one-use-proof');const body=await request.text();assert.equal(body,'{"current_password":"","value":"<script>"}');assert.equal(calls[0].data.method,'POST');assert.equal(calls[0].data.path,'/admin/v1/database/reveal');const bytes=await webcrypto.subtle.digest('SHA-256',new TextEncoder().encode(body));assert.equal(calls[0].data.digest,Buffer.from(bytes).toString('hex'));assert.doesNotMatch(source,/localStorage|sessionStorage|eval\(/)});
test('passkey browser client cannot send assertions to external hosts',async()=>{const tools=client(()=>{throw Error('network must not be reached')});await assert.rejects(tools.prepare('https://attacker.test/steal',{method:'POST'},true),/外部网站/)});
test('sensitive UI uses one shared script and offers password fallback',()=>{const account=readFileSync(new URL('../components/account-experience.tsx',import.meta.url),'utf8');assert.match(account,/使用通行密钥登录/);assert.match(account,/添加通行密钥/);assert.match(account,/密码确认/);assert.match(account,/通行密钥确认/);assert.match(account,/confirmationMethod!=='passkey'/);const admin=readFileSync(new URL('../../internal/web/assets/index.html',import.meta.url),'utf8');assert.match(admin,/\/ui\/passkeys.js/)});
