'use client';
import {formatSiteDate,siteDateInputToISO} from '../../lib/site-time';
import {useEffect,useRef,useState,type FormEvent} from 'react';
type Log={id:string;api_name:string;method:string;path:string;client_ip:string;status:number;price_micros:number;duration_ms:number;created_at:string;request_id:string;trace_id:string;credential_id:string};
type Page={items:Log[];total:number;page:number;page_size:number};
const money=(v:number)=>((v||0)/1000000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:6});
export default function CallLogs(){
 const [data,setData]=useState<Page>({items:[],total:0,page:1,page_size:20}),[page,setPage]=useState(1),[filters,setFilters]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState<Log|null>(null);const modal=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');const params=new URLSearchParams({...filters,page:String(page),page_size:'20'});fetch('/account/v1/logs?'+params,{credentials:'same-origin',cache:'no-store',signal:controller.signal}).then(async r=>{const v=await r.json();if(!r.ok)throw new Error(v.error||'日志读取失败');return v}).then(v=>{if(!controller.signal.aborted)setData(v)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[page,filters]);
 useEffect(()=>{if(detail)modal.current?.showModal();else modal.current?.close()},[detail]);
 function search(e:FormEvent<HTMLFormElement>){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;for(const key of ['from','to']){if(values[key])values[key]=siteDateInputToISO(values[key]);else delete values[key]}setFilters(values);setPage(1)}
 return <div className="account-call-logs"><section className="card"><h2>筛选调用日志</h2><p>仅显示自己的调用记录。筛选、状态、详情与管理后台保持一致；不保存请求正文、响应正文或密钥。</p><form className="account-filter" onSubmit={search}><label>搜索接口、路径或 IP<input name="search" maxLength={200}/></label><label>请求方法<select name="method"><option value="">全部方法</option>{['GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS'].map(v=><option key={v}>{v}</option>)}</select></label><label>状态码<select name="status"><option value="">全部状态</option><option value="2xx">成功 2xx</option><option value="3xx">重定向 3xx</option><option value="4xx">请求错误 4xx</option><option value="5xx">服务错误 5xx</option></select></label><label>开始时间<input name="from" type="datetime-local"/></label><label>结束时间<input name="to" type="datetime-local"/></label><label>请求 ID<input name="request_id" maxLength={128}/></label><div className="account-actions"><button disabled={busy}>查询</button><button type="reset" disabled={busy} onClick={()=>{setFilters({});setPage(1)}}>重置</button></div></form></section>{error&&<p role="alert" className="account-message">{error}</p>}
 <div className="account-table" aria-busy={busy}><table><thead><tr>{['时间','接口 / 路径','方法 / 状态','IP','费用 / 耗时','详情'].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{data.items.map(log=><tr key={log.id}><td>{formatSiteDate(log.created_at)}</td><td><strong>{log.api_name||'未匹配接口'}</strong><br/><code>{log.path}</code></td><td>{log.method}<br/><span className={'account-status'+(log.status>=400?' error':'')}>{log.status}</span></td><td>{log.client_ip||'—'}</td><td>¥ {money(log.price_micros)}<br/>{log.duration_ms} ms</td><td><button type="button" onClick={()=>setDetail(log)}>查看详情</button></td></tr>)}{!data.items.length&&!busy&&<tr><td colSpan={6}>暂无符合条件的调用记录。</td></tr>}</tbody></table></div>{busy&&<p role="status">正在读取日志…</p>}<div className="account-pager"><span>共 {data.total} 条 · 第 {data.page} / {Math.max(1,Math.ceil(data.total/data.page_size))} 页</span><div className="account-actions"><button disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>上一页</button><button disabled={busy||page*data.page_size>=data.total} onClick={()=>setPage(p=>p+1)}>下一页</button></div></div>
 <dialog className="account-dialog" ref={modal} aria-label="调用日志详情" onCancel={()=>setDetail(null)}><h2>调用日志详情</h2>{detail&&<dl className="account-log-detail">{[['接口',detail.api_name],['请求方法',detail.method],['路径',detail.path],['状态',String(detail.status)],['调用 IP',detail.client_ip],['请求 ID',detail.request_id],['链路 ID',detail.trace_id],['凭据 ID',detail.credential_id],['费用','¥ '+money(detail.price_micros)],['耗时',detail.duration_ms+' ms']].map(([name,value])=><div key={name}><dt>{name}</dt><dd><code>{value||'—'}</code></dd></div>)}</dl>}<button onClick={()=>setDetail(null)}>关闭详情</button></dialog></div>
}
