'use client';

import {useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import './account.css';
import CallLogs from './call-logs';
import {validPasswordBytes} from '../../lib/account-validation';
import {ShieldCheck,Wallet,KeyRound,History,UserRound,LogOut,Package,Monitor,ArrowLeft} from 'lucide-react';

type Options={registration?:boolean;email_login?:boolean;github?:boolean;google?:boolean;turnstile?:boolean;turnstile_site_key?:string;admin_path?:string};
type Profile={uid:string;nickname:string;email_verified:boolean;totp_enabled:boolean;user:{id:string;username:string;email:string};levels:{name:string;display_name:string}[];permissions:string[]};
type Plan={id:string;name:string;description:string;price_micros:number;days:number;hourly:number;daily:number;monthly:number};
type WalletData={wallet:{balance_micros:number;held_micros:number};subscription:(Plan&{plan_name:string;expires_at:string})|null;usage?:{hourly:number;daily:number;monthly:number}};
type Row=Record<string,any>;
type CaptchaAPI={render:(el:HTMLElement,args:Record<string,unknown>)=>string;remove:(id:string)=>void};
declare global {interface Window{turnstile?:CaptchaAPI}}
class RequestError extends Error{constructor(message:string,readonly status:number){super(message)}}
const money=(value:number)=>((value||0)/1000000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:6});
const date=(value:string)=>value?new Date(value).toLocaleString('zh-CN'):'—';
async function api<T=any>(path:string,method='GET',body?:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch(path,{method,credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json','X-API-Request':'1'},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:signal||AbortSignal.timeout(15000)});
 const data=await response.json().catch(()=>({}));if(!response.ok)throw new RequestError(data.error||'操作未完成，请稍后重试',response.status);return data;
}
function broadcast(){const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('api-manager-auth'):null;channel?.postMessage('changed');channel?.close()}
function useCaptcha(){const [token,setToken]=useState(''),[epoch,setEpoch]=useState(0);const reset=()=>{setToken('');setEpoch(n=>n+1)};return {token,onToken:setToken,epoch,reset}}
function Captcha({options,action,control}:{options:Options;action:string;control:ReturnType<typeof useCaptcha>}){
 const ref=useRef<HTMLDivElement>(null);const {onToken,epoch}=control;
 useEffect(()=>{
  if(!options.turnstile)return;let cancelled=false,id:string|undefined;
  const attach=()=>{if(window.turnstile&&ref.current&&!cancelled&&id===undefined)id=window.turnstile.render(ref.current,{sitekey:options.turnstile_site_key,action,callback:onToken,'expired-callback':()=>onToken(''),'error-callback':()=>onToken(''),theme:'light'})};
  let script=document.getElementById('turnstile-script') as HTMLScriptElement|null;
  if(!script){script=document.createElement('script');script.id='turnstile-script';script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.async=true;document.head.appendChild(script)}
  script.addEventListener('load',attach);attach();return()=>{cancelled=true;script?.removeEventListener('load',attach);if(id!==undefined)window.turnstile?.remove(id)};
 },[options.turnstile,options.turnstile_site_key,action,onToken,epoch]);
 return options.turnstile?<div ref={ref} className="account-captcha" aria-label="人机验证"/>:null;
}
function Dialog({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open&&!ref.current?.open)ref.current?.showModal();if(!open&&ref.current?.open)ref.current?.close()},[open]);
 return <dialog ref={ref} className="account-dialog" onCancel={e=>{e.preventDefault();onClose()}} aria-label={title}><h2>{title}</h2>{children}</dialog>;
}
function Fields({totp,required=true}:{totp:boolean;required?:boolean}){return <><label>当前密码<input name="current_password" type="password" autoComplete="current-password" maxLength={72} required={required}/></label>{totp&&<label>动态码或恢复码<input name="totp_code" autoComplete="one-time-code" maxLength={64} required={required}/></label>}</>}
function stepup(fields:FormData,token:string){return {current_password:String(fields.get('current_password')||''),totp_code:String(fields.get('totp_code')||''),turnstile_token:token}}
const tabs=[['overview','账户概览',Wallet],['basic','基础资料',UserRound],['plans','套餐',Package],['ledger','余额流水',History],['keys','调用凭据',KeyRound],['logs','调用日志',History],['security','账号安全',ShieldCheck],['sessions','设备与会话',Monitor]] as const;

export default function AccountPage(){
 const [options,setOptions]=useState<Options>({}),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[view,setView]=useState('overview'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[wallet,setWallet]=useState<WalletData|null>(null),[rows,setRows]=useState<Row[]>([]),[newKey,setNewKey]=useState(''),[recovery,setRecovery]=useState<string[]>([]),[dataLoading,setDataLoading]=useState(false);
 const lock=useRef(false),identity=useRef(''),generation=useRef(0);
 const refresh=useCallback(async()=>{const epoch=++generation.current;try{const next=await api<Profile>('/account/v1/me');if(epoch===generation.current){if(identity.current&&identity.current!==next.uid){setNewKey('');setRecovery([]);setRows([]);setWallet(null);setView('overview')};identity.current=next.uid;setProfile(next)}}catch(e){if(epoch===generation.current&&e instanceof RequestError&&e.status===401){identity.current='';setProfile(null);setNewKey('');setRows([]);setWallet(null)}else if(epoch===generation.current)setMessage('暂时无法确认登录状态，请刷新重试')}finally{if(epoch===generation.current)setLoading(false)}},[]);
 useEffect(()=>{void api<Options>('/account/v1/options').then(setOptions).catch(()=>setMessage('登录配置暂不可用'));void refresh();const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('api-manager-auth'):null;const update=()=>void refresh();channel?.addEventListener('message',update);window.addEventListener('focus',update);return()=>{++generation.current;channel?.close();window.removeEventListener('focus',update)}},[refresh]);
 const loadData=useCallback(async(signal?:AbortSignal)=>{
  const uid=identity.current;if(!uid)return;setDataLoading(true);setRows([]);try{
   const endpoints:Record<string,string>={ledger:'/account/v1/wallet/ledger',plans:'/account/v1/plans',keys:'/account/v1/keys',sessions:'/account/v1/sessions'};
   if(view==='overview'||view==='plans'){const next=await api<WalletData>('/account/v1/wallet','GET',undefined,signal);if(identity.current===uid&&!signal?.aborted)setWallet(next)}
   if(endpoints[view]){const next=await api<Row[]>(endpoints[view],'GET',undefined,signal);if(identity.current===uid&&!signal?.aborted)setRows(next||[])}
  }catch(e){if(!signal?.aborted&&identity.current===uid)setMessage(e instanceof Error?e.message:'数据读取失败')}finally{if(!signal?.aborted)setDataLoading(false)}
 },[view]);
 useEffect(()=>{const controller=new AbortController();setMessage('');void loadData(controller.signal);return()=>controller.abort()},[profile?.uid,loadData]);
 async function act(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e instanceof Error?e.message:'操作未完成')}finally{lock.current=false;setBusy(false)}}
 const adminPath=options.admin_path?.startsWith('/')&&!options.admin_path.startsWith('//')?options.admin_path:'/admin';
 return <main className="account-page"><link rel="stylesheet" href="/ui/admin.css"/><link rel="stylesheet" href="/ui/controls.css"/>
  <header className="account-header"><a href="/"><ArrowLeft size={17}/>接口目录</a><strong>用户中心</strong><div>{profile&&profile.permissions.some(p=>p==='*'||p==='api.read')&&<a href={adminPath+'/'}>管理后台</a>}{profile&&<button disabled={busy} onClick={()=>void act(async()=>{await api('/auth/v1/logout','POST');generation.current++;identity.current='';setProfile(null);setRows([]);setNewKey('');setWallet(null);setRecovery([]);broadcast()})}><LogOut size={16}/>退出登录</button>}</div></header>
  {message&&<p className="account-message" role="status" aria-live="polite">{message}</p>}
  {loading?<section className="account-state" role="status">正在确认登录状态…</section>:!profile?<Auth options={options} busy={busy} act={act} onLogin={async()=>{broadcast();await refresh()}} setMessage={setMessage}/>:<div className="account-layout">
   <aside className="account-sidebar"><strong>{profile.nickname||profile.user.username}</strong><small>{profile.user.email||'尚未设置邮箱'}</small><nav aria-label="用户中心导航">{tabs.map(([id,title,Icon])=><button key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined} onClick={()=>{setView(id);setNewKey('')}}><Icon size={18}/>{title}</button>)}</nav></aside>
   <section className="account-content" aria-busy={dataLoading}><h1>{tabs.find(t=>t[0]===view)?.[1]}</h1>
    {dataLoading?<p role="status">正在读取…</p>:<>
     {view==='overview'&&<><div className="account-stats"><section><span>可用余额</span><strong>¥ {money((wallet?.wallet.balance_micros||0)-(wallet?.wallet.held_micros||0))}</strong><small>预留金额 ¥ {money(wallet?.wallet.held_micros||0)}</small></section><section><span>当前套餐</span><strong>{wallet?.subscription?.plan_name||'按次计费'}</strong><small>{wallet?.subscription?'有效至 '+date(wallet.subscription.expires_at):'按接口公示价格结算'}</small></section><section><span>账号保护</span><strong>{profile.totp_enabled?'双重验证已启用':'建议开启双重验证'}</strong><small>{profile.email_verified?'邮箱已验证':'邮箱待验证'}</small></section></div><dl className="account-details"><div><dt>唯一 UID</dt><dd>{profile.uid}</dd></div><div><dt>用户等级</dt><dd>{profile.levels.filter(level=>(profile as any).user.roles?.includes(level.name)||(profile as any).user.role===level.name).map(level=>level.display_name||level.name).join('、')||'会员'}</dd></div></dl>{wallet?.subscription&&<p>套餐额度：每小时 {wallet.subscription.hourly||'不限'} 次（已用 {wallet.usage?.hourly||0}） / 每日 {wallet.subscription.daily||'不限'} 次（已用 {wallet.usage?.daily||0}） / 每月 {wallet.subscription.monthly||'不限'} 次（已用 {wallet.usage?.monthly||0}）。按北京时间的自然周期计算。</p>}</>}
     {view==='basic'&&<><p>昵称用于展示；UID 自动生成，不可修改。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api('/account/v1/basic','PUT',{nickname:f.get('nickname')});await refresh();setMessage('资料已保存')})}}><label>昵称<input name="nickname" defaultValue={profile.nickname} maxLength={64} required/></label><label>唯一 UID<input value={profile.uid} readOnly/></label><label>邮箱<input value={profile.user.email||'尚未设置'} readOnly/></label><button className="account-primary" disabled={busy}>保存昵称</button></form><p>修改邮箱、用户名与密码，请进入账号安全。</p>{profile.user.email&&!profile.email_verified&&<VerifyEmail options={options} email={profile.user.email} busy={busy} act={act} refresh={refresh} setMessage={setMessage}/>}</>}
     {view==='plans'&&<Plans plans={rows as Plan[]} wallet={wallet} busy={busy} act={act} reload={loadData} setMessage={setMessage}/>}
     {view==='keys'&&<Keys key={profile.uid} rows={rows} options={options} profile={profile} busy={busy} act={act} reload={loadData} secret={newKey} setSecret={value=>{if(identity.current===profile.uid)setNewKey(value)}}/>}
     {view==='ledger'&&<Table headers={['时间','类型 / 原因','金额','余额']} rows={rows.map(v=>[date(v.created_at),v.note||v.kind,'¥ '+money(v.amount_micros),'¥ '+money(v.balance_micros)])} empty="暂无余额流水。"/>}
     {view==='logs'&&<CallLogs key={profile.uid}/>}
     {view==='sessions'&&<Sessions key={profile.uid} profile={profile} options={options} rows={rows} busy={busy} act={act} reload={loadData} refresh={refresh}/>}
     {view==='security'&&<Security key={profile.uid} profile={profile} options={options} busy={busy} act={act} refresh={refresh} setMessage={setMessage} setRecovery={codes=>{if(!identity.current||identity.current===profile.uid)setRecovery(codes)}}/>}
    </>}
   </section>
  </div>}
  <Dialog open={recovery.length>0} title="请保存恢复码" onClose={()=>{}}><p>以下恢复码仅显示一次。每个码只能使用一次，请离线保存。安全设置已更新，需重新登录。</p><div className="account-secret">{recovery.map(code=><code key={code}>{code}</code>)}</div><button onClick={()=>setRecovery([])}>我已保存，返回登录</button></Dialog>
 </main>;
}

function Auth({options,busy,act,onLogin,setMessage}:{options:Options;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;onLogin:()=>Promise<void>;setMessage:(s:string)=>void}){
 const [mode,setMode]=useState('password'),[step,setStep]=useState('login'),[verification,setVerification]=useState(''),[challenge,setChallenge]=useState(''),[resetToken,setResetToken]=useState(''),[recoverable,setRecoverable]=useState(false),[sentEmail,setSentEmail]=useState('');const form=useRef<HTMLFormElement>(null);const captcha=useCaptcha(),emailCaptcha=useCaptcha(),oauthCaptcha=useCaptcha();
 useEffect(()=>{const params=new URLSearchParams(location.search);if(params.get('mfa')==='1')setStep('mfa');else if(params.get('recover')==='1')setStep('forgot');const match=location.hash.match(/^#reset=([0-9a-f]{64})$/);if(match){setResetToken(match[1]);setStep('reset');history.replaceState(null,'',location.pathname)}void api('/auth/v1/recovery').then(v=>setRecoverable(v.enabled)).catch(()=>{})},[]);
 function change(next:string){setStep(next);setChallenge('');setVerification('');setSentEmail('');captcha.reset();emailCaptcha.reset();setMessage('');form.current?.reset()}
 const action=step==='register'?'register':step==='forgot'?'forgot_password':step==='reset'?'reset_password':mode==='email'?'email_login':'login';
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);await act(async()=>{try{
  let result:any;
  if((step==='register'||step==='reset')&&!validPasswordBytes(String(fields.get('password')||'')))throw new Error('密码须为 8–72 个 UTF-8 字节');
  if(step==='mfa')result=await api('/account/v1/mfa-login','POST',{challenge_id:challenge,totp_code:fields.get('totp_code')});
  else if(step==='forgot'){await api('/auth/v1/forgot-password','POST',{email:fields.get('email'),turnstile_token:captcha.token});setMessage('若邮箱匹配可用账号，将发送重置链接。请检查收件箱。');return}
  else if(step==='reset'){await api('/auth/v1/reset-password','POST',{token:resetToken,password:fields.get('password'),totp_code:fields.get('totp_code'),turnstile_token:captcha.token});setResetToken('');change('login');setMessage('密码已重置，请重新登录');return}
  else if(step==='register'){if(String(fields.get('email'))!==sentEmail)throw new Error('邮箱已变化，请重新获取验证码');await api('/account/v1/register','POST',{username:fields.get('username'),nickname:fields.get('nickname'),email:fields.get('email'),password:fields.get('password'),code:fields.get('code'),verification_id:verification,turnstile_token:captcha.token});change('login');setMessage('注册完成，请登录');return}
  else if(mode==='email'){if(String(fields.get('email'))!==sentEmail)throw new Error('邮箱已变化，请重新获取验证码');result=await api('/account/v1/email-login','POST',{verification_id:verification,code:fields.get('code'),turnstile_token:captcha.token})}
  else result=await api('/auth/v1/login','POST',{username:fields.get('username'),password:fields.get('password'),turnstile_token:captcha.token});
  if(result.mfa_required){setChallenge(result.challenge_id);setStep('mfa');form.current?.reset();return}form.current?.reset();await onLogin();const destination=new URLSearchParams(location.search).get('return');if(destination==='docs')location.assign('/');else if(destination==='admin'){const path=options.admin_path||'/admin';if(path.startsWith('/')&&!path.startsWith('//'))location.assign(path+'/')};
 }finally{captcha.reset()}})}
 async function sendCode(){await act(async()=>{try{const email=form.current?.querySelector<HTMLInputElement>('[name=email]')?.value||'';if(!email)throw new Error('请填写邮箱');const result=await api('/account/v1/send-code','POST',{email,purpose:step==='register'?'register':'email-login',turnstile_token:emailCaptcha.token});setVerification(result.verification_id);setSentEmail(email);setMessage(result.message)}finally{emailCaptcha.reset()}})}
 async function oauth(provider:string){await act(async()=>{try{const result=await api('/account/v1/oauth/'+provider+'/start','POST',{turnstile_token:oauthCaptcha.token});const url=new URL(result.url);if(url.protocol!=='https:'||!['github.com','accounts.google.com'].includes(url.hostname))throw new Error('授权地址不可用');location.assign(result.url)}finally{oauthCaptcha.reset()}})}
 const title={login:'登录账号',register:'创建账号',mfa:'双重验证',forgot:'找回密码',reset:'重置密码'}[step];
 return <section className="account-auth"><div className="account-auth-intro"><ShieldCheck size={36}/><h1>每次调用，清晰可控</h1><p>管理余额、套餐、调用记录与账号安全。</p><ul><li>费用与余额流水有据可查</li><li>按小时、每日、每月掌握额度</li><li>前台与后台共享登录状态</li></ul></div><div className="account-auth-form"><h2>{title}</h2>{step==='login'&&options.email_login&&<div className="account-mode"><button disabled={busy} aria-pressed={mode==='password'} onClick={()=>{setMode('password');change('login')}}>密码登录</button><button disabled={busy} aria-pressed={mode==='email'} onClick={()=>{setMode('email');change('login')}}>邮箱验证码</button></div>}
 <form ref={form} onSubmit={submit} key={step+mode}>
  {step==='mfa'?<><p>输入验证器动态码，或一个未使用的恢复码。验证失败后须重新开始登录。</p><label>动态码或恢复码<input name="totp_code" autoComplete="one-time-code" maxLength={64} required/></label></>:<>
   {(step==='register'||(step==='login'&&mode==='password'))&&<label>用户名<input name="username" autoComplete="username" minLength={3} maxLength={64} required/></label>}
   {step==='register'&&<label>昵称<input name="nickname" maxLength={64} required/></label>}
   {(step==='register'||step==='forgot'||(step==='login'&&mode==='email'))&&<label>邮箱<input name="email" type="email" autoComplete="email" maxLength={254} required/></label>}
   {(step==='register'||(step==='login'&&mode==='email'))&&<><Captcha options={options} action="email_code" control={emailCaptcha}/><button type="button" disabled={busy||!!options.turnstile&&!emailCaptcha.token} onClick={()=>void sendCode()}>发送邮箱验证码</button><label>邮箱验证码<input name="code" autoComplete="one-time-code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></label></>}
   {(step==='register'||step==='reset'||(step==='login'&&mode==='password'))&&<label>{step==='reset'?'新密码':'密码'}<input name="password" type="password" autoComplete={step==='login'?'current-password':'new-password'} maxLength={72} required/><small>8–72 字节；中文字符会占用多个字节。</small></label>}
   {step==='reset'&&<label>动态码或恢复码（已启用双重验证时必填）<input name="totp_code" autoComplete="one-time-code" maxLength={64}/></label>}
   <Captcha options={options} action={action} control={captcha}/>
  </>}
  <button className="account-primary" disabled={busy||step!=='mfa'&&!!options.turnstile&&!captcha.token}>{busy?'正在处理…':title}</button>
 </form>
 {step==='login'&&(options.github||options.google)&&<><Captcha options={options} action="oauth" control={oauthCaptcha}/><div className="account-social">{options.github&&<button disabled={busy||!!options.turnstile&&!oauthCaptcha.token} onClick={()=>void oauth('github')}>GitHub 登录</button>}{options.google&&<button disabled={busy||!!options.turnstile&&!oauthCaptcha.token} onClick={()=>void oauth('google')}>Google 登录</button>}</div></>}
 <div className="account-auth-links">{step==='login'?<>{options.registration&&<button disabled={busy} onClick={()=>change('register')}>注册账号</button>}{recoverable&&<button disabled={busy} onClick={()=>change('forgot')}>忘记密码</button>}</>:<button disabled={busy} onClick={()=>change('login')}>返回登录</button>}</div>
 </div></section>;
}
function Table({headers,rows,empty}:{headers:string[];rows:ReactNode[][];empty:string}){return rows.length?<div className="account-table"><table><thead><tr>{headers.map(header=><th key={header} scope="col">{header}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>:<p className="account-empty">{empty}</p>}
function Plans({plans,wallet,busy,act,reload,setMessage}:{plans:Plan[];wallet:WalletData|null;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>;setMessage:(s:string)=>void}){
 const [purchase,setPurchase]=useState<{plan:Plan;operation:string}|null>(null);
 return <><p>有效套餐覆盖已成功调用的接口费用。额度用尽时不会自动改为余额扣费。未购买套餐时，按接口价格结算。</p>{wallet?.subscription&&<p>当前套餐到期：{date(wallet.subscription.expires_at)}。续购将在到期后生效。</p>}<div className="account-plan-grid">{plans.map(plan=><section key={plan.id}><h2>{plan.name}</h2><p>{plan.description}</p><strong>¥ {money(plan.price_micros)} <small>/ {plan.days} 天</small></strong><ul><li>每小时 {plan.hourly||'不限'} 次</li><li>每日 {plan.daily||'不限'} 次</li><li>每月 {plan.monthly||'不限'} 次</li></ul><button disabled={busy} onClick={()=>setPurchase({plan,operation:crypto.randomUUID()})}>{wallet?.subscription?'续购套餐':'购买套餐'}</button></section>)}</div>{!plans.length&&<p>暂未提供套餐，可按接口价格调用。</p>}
 <Dialog open={!!purchase} title="确认购买套餐" onClose={()=>{if(!busy)setPurchase(null)}}><p>购买 {purchase?.plan.name} 将从余额扣除 ¥ {money(purchase?.plan.price_micros||0)}。套餐生效后按公示额度使用。</p><p>若请求超时，请使用“重试此购买”，不要关闭窗口后重复购买。</p><div className="account-actions"><button disabled={busy} onClick={()=>setPurchase(null)}>取消</button><button disabled={busy} onClick={()=>void act(async()=>{if(!purchase)return;await api('/account/v1/subscription','POST',{plan_id:purchase.plan.id,operation_id:purchase.operation,confirm:true});setPurchase(null);await reload();setMessage('套餐购买完成')})}>确认 / 重试此购买</button></div></Dialog></>;
}
function Keys({rows,options,profile,busy,act,reload,secret,setSecret}:{rows:Row[];options:Options;profile:Profile;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>;secret:string;setSecret:(s:string)=>void}){
 const [target,setTarget]=useState<Row|null>(null),[operation,setOperation]=useState<'reveal'|'revoke'>('reveal');const createCaptcha=useCaptcha(),manageCaptcha=useCaptcha();
 const open=(key:Row,kind:'reveal'|'revoke')=>{setSecret('');setOperation(kind);setTarget(key);manageCaptcha.reset()};
 return <><p>密钥加密保存。可以再次查看自己的有效密钥，每次查看均须重新验证并记录审计。不要放入公开网页或代码仓库。</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,f=new FormData(form);void act(async()=>{try{const result=await api('/account/v1/keys','POST',{key_name:f.get('key_name'),...stepup(f,createCaptcha.token)});setSecret(result.api_key);form.reset();await reload()}finally{createCaptcha.reset()}})}}><label>凭据名称<input name="key_name" maxLength={64} required/></label><Fields totp={profile.totp_enabled}/><Captcha options={options} action="sensitive" control={createCaptcha}/><button disabled={busy||!!options.turnstile&&!createCaptcha.token}>创建密钥</button></form>{secret&&<div className="account-secret"><h3>调用密钥</h3><code>{secret}</code><button onClick={()=>setSecret('')}>关闭并隐藏密钥</button></div>}
 <Table headers={['名称','前缀','创建时间','状态','操作']} rows={rows.map(key=>[key.name,key.prefix,date(key.created_at),key.revoked?'已吊销':key.expires_at&&new Date(key.expires_at).getTime()<Date.now()?'已过期':'可使用',<div className="account-actions"><button disabled={busy||key.revoked||!key.api_key_available} onClick={()=>open(key,'reveal')}>查看密钥</button><button disabled={busy||key.revoked} onClick={()=>open(key,'revoke')}>吊销</button></div>])} empty="尚未创建调用凭据。"/>
 <Dialog open={!!target} title={operation==='reveal'?'验证并查看调用密钥':'吊销调用凭据'} onClose={()=>{if(!busy)setTarget(null)}}><p>{operation==='reveal'?'验证后，仅在当前页面显示此密钥。请确认环境安全。':'吊销后，使用该密钥的程序将无法调用接口。'} {target?.name}</p><form key={(target?.id||'')+operation} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{try{if(operation==='reveal'){const result=await api('/account/v1/keys/'+encodeURIComponent(target!.id)+'/reveal','POST',stepup(f,manageCaptcha.token));setSecret(result.api_key)}else{await api('/account/v1/keys/'+encodeURIComponent(target!.id),'DELETE',stepup(f,manageCaptcha.token));await reload()}setTarget(null)}finally{manageCaptcha.reset()}})}}><Fields totp={profile.totp_enabled}/><Captcha options={options} action="sensitive" control={manageCaptcha}/><div className="account-actions"><button type="button" disabled={busy} onClick={()=>setTarget(null)}>取消</button><button disabled={busy||!!options.turnstile&&!manageCaptcha.token}>{operation==='reveal'?'验证并查看':'验证并吊销'}</button></div></form></Dialog></>;
}

function Sessions({rows,profile,options,busy,act,reload,refresh}:{rows:Row[];profile:Profile;options:Options;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;reload:()=>Promise<void>;refresh:()=>Promise<void>}){
 const [target,setTarget]=useState<Row|null>(null),[people,setPeople]=useState<Row[]>([]),[selected,setSelected]=useState(profile.uid),[remote,setRemote]=useState<Row[]|null>(null),[error,setError]=useState('');const captcha=useCaptcha();const administrator=profile.permissions.includes('*');
 useEffect(()=>{if(administrator)void api<Row[]>('/account/v1/session-users').then(setPeople).catch(e=>setError(e.message))},[administrator]);
 const load=async(id:string)=>{setError('');try{setRemote(await api('/account/v1/sessions?user_id='+encodeURIComponent(id)))}catch(e){setError(e instanceof Error?e.message:'会话读取失败')}};
 const list=remote||rows;return <>{administrator&&<form onSubmit={e=>e.preventDefault()}><label>管理用户的登录会话<select value={selected} onChange={e=>{setSelected(e.target.value);void load(e.target.value)}}>{people.map(u=><option key={u.id} value={u.id}>{u.nickname||u.username}</option>)}</select></label></form>}<p>退出会话后，该设备须重新登录。个人会话和管理员全站会话管理统一在此处。</p>{error&&<p className="account-message" role="alert">{error}</p>}<Table headers={['设备','登录 IP','最近活动','有效期','状态','操作']} rows={list.map(s=>[s.device||'未知设备',s.login_ip||'未知',date(s.last_seen_at),date(s.expires_at),s.current?'当前设备':'其他设备',<button disabled={busy} onClick={()=>{captcha.reset();setTarget(s)}}>退出会话</button>])} empty="没有可用会话。"/>
 <Dialog open={!!target} title="退出登录会话" onClose={()=>{if(!busy)setTarget(null)}}><p>确认退出 {target?.device||'此设备'}？</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{try{await api('/account/v1/sessions/'+encodeURIComponent(target!.id),'DELETE',{confirm:true,user_id:selected,...(selected!==profile.uid?stepup(f,captcha.token):{})});setTarget(null);await refresh();if(selected===profile.uid){await reload();setRemote(null)}else await load(selected);broadcast()}finally{captcha.reset()}})}}>{selected!==profile.uid&&<><Fields totp={profile.totp_enabled}/><Captcha options={options} action="sensitive" control={captcha}/></>}<div className="account-actions"><button type="button" disabled={busy} onClick={()=>setTarget(null)}>取消</button><button disabled={busy||selected!==profile.uid&&!!options.turnstile&&!captcha.token}>确认退出</button></div></form></Dialog></>;
}

function Security({profile,options,busy,act,refresh,setMessage,setRecovery}:{profile:Profile;options:Options;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>;setMessage:(s:string)=>void;setRecovery:(s:string[])=>void}){
 const [setup,setSetup]=useState<{secret:string;uri:string}|null>(null),[identities,setIdentities]=useState<string[]>([]),[emailProof,setEmailProof]=useState(''),[proofEmail,setProofEmail]=useState('');const totpCaptcha=useCaptcha(),profileCaptcha=useCaptcha(),emailCaptcha=useCaptcha(),linkCaptcha=useCaptcha();const profileForm=useRef<HTMLFormElement>(null),identityForm=useRef<HTMLFormElement>(null);
 useEffect(()=>{void api<string[]>('/account/v1/identities').then(setIdentities).catch(()=>{});return()=>setSetup(null)},[profile.uid]);
 async function changeIdentity(provider:string,link:boolean){const fields=new FormData(identityForm.current!);await act(async()=>{try{if(link){const result=await api('/account/v1/oauth/'+provider+'/start','POST',{purpose:'link',...stepup(fields,linkCaptcha.token)});const url=new URL(result.url);if(url.protocol!=='https:'||!['github.com','accounts.google.com'].includes(url.hostname))throw new Error('授权地址不可用');location.assign(result.url)}else{if(!window.confirm('确认解绑 '+provider+' 登录？请确保已记住账号密码。'))return;await api('/account/v1/identities/'+provider,'DELETE',stepup(fields,linkCaptcha.token));setIdentities(await api('/account/v1/identities'));setMessage('授权账号已解绑')}}finally{linkCaptcha.reset()}})}
 return <div className="account-security"><section><h2>验证器双重验证</h2><p>{profile.totp_enabled?'每次登录需要动态码或恢复码。关闭后，已有会话将退出。':'使用兼容 TOTP 的验证器应用绑定。绑定信息有效期为 10 分钟。'}</p><form onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);void act(async()=>{try{const result=await api('/account/v1/totp','POST',{purpose:profile.totp_enabled?'disable':setup?'enable':'begin',...stepup(fields,totpCaptcha.token)});if(result.secret)setSetup(result);else{setSetup(null);setRecovery(result.recovery_codes||[]);broadcast();await refresh();setMessage('安全设置已更新，请重新登录')}}finally{totpCaptcha.reset()}})}}><Fields totp={profile.totp_enabled}/>{setup&&<label>验证器动态码<input name="totp_code" inputMode="numeric" pattern="[0-9]{6}" autoComplete="one-time-code" maxLength={6} required/></label>}<Captcha options={options} action="sensitive" control={totpCaptcha}/><button disabled={busy||!!options.turnstile&&!totpCaptcha.token}>{profile.totp_enabled?'验证并关闭':setup?'验证并启用':'开始绑定'}</button></form>{setup&&<div className="account-secret"><h3>在验证器中手动添加</h3><code>{setup.secret}</code><p>账号：{profile.user.username}<br/>算法 SHA1，6 位数字，每 30 秒更新。请勿把绑定密钥发送给他人。</p></div>}</section>
 <section><h2>修改账号信息</h2><p>修改用户名、邮箱或密码后，所有设备须重新登录。修改邮箱还需验证新邮箱。</p><form ref={profileForm} onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget),email=String(fields.get('email'));void act(async()=>{try{if(fields.get('password')&&!validPasswordBytes(String(fields.get('password'))))throw new Error('新密码须为 8–72 个 UTF-8 字节');if(email!==profile.user.email&&email!==proofEmail)throw new Error('请先验证新邮箱');await api('/auth/v1/me','PUT',{username:fields.get('username'),email,...(fields.get('password')?{password:fields.get('password')}:{}),verification_id:emailProof,verification_code:fields.get('code'),...stepup(fields,profileCaptcha.token)});broadcast();await refresh();setMessage('账号已更新，请重新登录')}finally{profileCaptcha.reset()}})}}><label>用户名<input name="username" defaultValue={profile.user.username} minLength={3} maxLength={64} required/></label><label>邮箱<input name="email" type="email" defaultValue={profile.user.email} maxLength={254} required/></label><Captcha options={options} action="email_code" control={emailCaptcha}/><button type="button" disabled={busy||!!options.turnstile&&!emailCaptcha.token} onClick={()=>void act(async()=>{try{const email=profileForm.current?.querySelector<HTMLInputElement>('[name=email]')?.value;if(!email)throw new Error('请填写邮箱');const result=await api('/account/v1/send-code','POST',{email,purpose:'change-email',turnstile_token:emailCaptcha.token});setEmailProof(result.verification_id);setProofEmail(email);setMessage('验证码已发送至新邮箱')}finally{emailCaptcha.reset()}})}>发送新邮箱验证码</button><label>新邮箱验证码（修改邮箱时必填）<input name="code" autoComplete="one-time-code" inputMode="numeric" maxLength={6}/></label><label>新密码（不修改时留空）<input name="password" type="password" autoComplete="new-password" maxLength={72}/></label><Fields totp={profile.totp_enabled}/><Captcha options={options} action="sensitive" control={profileCaptcha}/><button disabled={busy||!!options.turnstile&&!profileCaptcha.token}>验证并保存</button></form></section>
 {(options.github||options.google||identities.length>0)&&<section><h2>第三方登录</h2><p>首次通过第三方登录的用户，可使用找回密码设置本地密码，再绑定验证器或管理授权账号。</p><p>授权账号只能绑定到当前登录用户，不会根据邮箱自动合并账号。解绑前请确保已设置可用密码。</p><form ref={identityForm} onSubmit={e=>e.preventDefault()}><Fields totp={profile.totp_enabled}/><Captcha options={options} action="oauth" control={linkCaptcha}/><div className="account-actions">{['github','google'].filter(p=>identities.includes(p)||options[p as 'github'|'google']).map(provider=><button type="button" key={provider} disabled={busy||!!options.turnstile&&!linkCaptcha.token} onClick={()=>void changeIdentity(provider,!identities.includes(provider))}>{identities.includes(provider)?'解绑':'绑定'} {provider==='github'?'GitHub':'Google'}</button>)}</div></form></section>}
 </div>;
}

function VerifyEmail({options,email,busy,act,refresh,setMessage}:{options:Options;email:string;busy:boolean;act:(f:()=>Promise<void>)=>Promise<void>;refresh:()=>Promise<void>;setMessage:(s:string)=>void}){const [proof,setProof]=useState('');const captcha=useCaptcha();return <section><h2>验证当前邮箱</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void act(async()=>{await api('/account/v1/verify-email','POST',{verification_id:proof,code:f.get('code')});await refresh();setMessage('邮箱已验证')})}}><Captcha options={options} action="email_code" control={captcha}/><button type="button" disabled={busy||!!options.turnstile&&!captcha.token} onClick={()=>void act(async()=>{try{const result=await api('/account/v1/send-code','POST',{email,purpose:'verify-email',turnstile_token:captcha.token});setProof(result.verification_id);setMessage('验证码已发送')}finally{captcha.reset()}})}>发送验证邮件</button><label>邮箱验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} required/></label><button disabled={busy||!proof}>确认邮箱验证码</button></form></section>}
