{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api-manager.fullname" . }}
  labels:
    {{- include "api-manager.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "api-manager.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ max 3 (mul (int .Values.replicaCount) 3) }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
{{- end }}
