ALTER TABLE apis ADD COLUMN IF NOT EXISTS auth_config JSONB NOT NULL DEFAULT '{}'::JSONB;
ALTER TABLE apis ADD COLUMN IF NOT EXISTS daily_quota INTEGER NOT NULL DEFAULT 0;
ALTER TABLE apis ADD COLUMN IF NOT EXISTS monthly_quota INTEGER NOT NULL DEFAULT 0;
ALTER TABLE apis ADD COLUMN IF NOT EXISTS upstream_url TEXT NOT NULL DEFAULT '';
ALTER TABLE apis ADD COLUMN IF NOT EXISTS upstream_path TEXT NOT NULL DEFAULT '';
ALTER TABLE apis ADD COLUMN IF NOT EXISTS strip_path BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS api_releases (
    id BIGSERIAL PRIMARY KEY,
    api_id TEXT NOT NULL REFERENCES apis(id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    snapshot JSONB NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_by UUID REFERENCES users(id),
    UNIQUE (api_id, version)
);
