ALTER TABLE apis ADD COLUMN IF NOT EXISTS public_visible BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE apis ADD COLUMN IF NOT EXISTS public_title TEXT NOT NULL DEFAULT '';
ALTER TABLE apis ADD COLUMN IF NOT EXISTS public_summary TEXT NOT NULL DEFAULT '';
ALTER TABLE apis ADD COLUMN IF NOT EXISTS public_category TEXT NOT NULL DEFAULT '';
