ALTER TABLE apis
    ADD COLUMN IF NOT EXISTS parameters_schema JSONB NOT NULL DEFAULT '{}'::JSONB,
    ADD COLUMN IF NOT EXISTS upstream_timeout_ms INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS upstream_retries INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS circuit_breaker_threshold INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS circuit_breaker_reset_seconds INTEGER NOT NULL DEFAULT 30;
