'use client';
import {LoadingPlaceholder} from '../../components/loading-placeholder';
import {useEffect,useState,type FormEvent} from 'react';
import '../account/account.css';
import {EmailField} from '../../components/email-field';
import {ProviderIcon} from '../../components/provider-icon';
import {validPassword} from '../../lib/account-validation';
async function request(path:string,body?:unknown){const r=await fetch(path,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',redirect:'error',headers:{'Content-Type':'application/json','X-API-Request':'1'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const result=await r.json().catch(()=>({}));if(!r.ok)throw Error(result.error||'操作未完成，请稍后重试');return result}
export default function CompleteRegistration(){const [pending,setPending]=useState<{nickname:string;allowed_email_domains:string[]}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[proof,setProof]=useState(''),[sentEmail,setSentEmail]=useState('');useEffect(()=>{void request('/account/v1/onboarding').then(setPending).catch(e=>setError(e.message))},[]);
 async function sendCode(){if(busy)return;setBusy(true);setError('');try{const result=await request('/account/v1/onboarding/send-code',{email});setProof(result.verification_id);setSentEmail(email);setNotice('验证码已发送，请在本次授权有效期内完成注册。')}catch(e){setError(e instanceof Error?e.message:'发送失败')}finally{setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);setError('');const password=String(f.get('password')||'');if(!validPassword(password)||password!==f.get('confirm_password')){setError('密码须为 8–24 个字符，两次输入须一致');return};if(!proof||sentEmail!==email){setError('请先获取当前邮箱的验证码');return};setBusy(true);try{await request('/account/v1/onboarding/complete',{username:f.get('username'),nickname:f.get('nickname'),email,password,verification_id:proof,code:f.get('code')});const target=new URLSearchParams(location.search).get('return'),paths:Record<string,string>={home:'/',docs:'/docs',guide:'/guide',playground:'/playground'};location.assign(paths[target||'']||'/account')}catch(e){setError(e instanceof Error?e.message:'注册未完成，请重新开始 Telegram 登录')}finally{setBusy(false)}}
 return <main className="account-page"><header className="account-header"><a href="/">网站首页</a><strong>完善账号资料</strong><a href="/login">返回登录</a></header><section className="account-auth"><div className="account-auth-intro"><ProviderIcon provider="telegram"/><h1>确认邮箱，完成首次登录</h1><p>Telegram 身份已确认。验证邮箱并设置本站登录资料后，才会创建可用账号。</p><p>不会根据已有邮箱自动合并账号。</p></div><div className="account-auth-form"><h2>绑定并验证邮箱</h2>{error&&<p role="alert" className="account-message">{error}</p>}{notice&&<p role="status">{notice}</p>}{pending?<form onSubmit={submit}><label>用户名<input name="username" minLength={3} maxLength={20} pattern="[a-zA-Z0-9]{3,20}" autoComplete="username" required disabled={busy}/></label><label>昵称<input name="nickname" maxLength={64} defaultValue={pending.nickname} required disabled={busy}/></label><EmailField domains={pending.allowed_email_domains} disabled={busy} onValue={value=>{setEmail(value);if(value!==sentEmail)setProof('')}}/><div className="email-code-row"><label>邮箱验证码<input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required disabled={busy}/></label><button type="button" disabled={busy||!email} onClick={()=>void sendCode()}>发送</button></div><label>登录密码<input name="password" type="password" autoComplete="new-password" maxLength={24} required disabled={busy}/></label><label>确认密码<input name="confirm_password" type="password" autoComplete="new-password" maxLength={24} required disabled={busy}/></label><button className="account-primary" disabled={busy||!proof}>{busy?'处理中…':'验证邮箱并完成注册'}</button></form>:!error?<LoadingPlaceholder compact/>:<a href="/login">重新登录</a>}</div></section></main>
}
